name: kwctl release
on:
  push:
    tags:
    - 'v*'
env:
  CARGO_TERM_COLOR: always
jobs:

  ci:
    # A branch is required, and cannot be dynamic - https://github.com/actions/runner/issues/1493
    uses: kubewarden/kwctl/.github/workflows/tests.yml@main

  build-linux-x86_64:
    name: Build linux (x86_64) binary
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
    - uses: actions/checkout@v2
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Setup musl for x86_64
      run: |
        curl https://musl.cc/x86_64-linux-musl-cross.tgz | tar -xz
        echo "$PWD/x86_64-linux-musl-cross/bin" >> $GITHUB_PATH
    - run: rustup target add x86_64-unknown-linux-musl
    - name: Build kwctl
      env:
        CC: x86_64-linux-musl-gcc
      run: cargo build --target=x86_64-unknown-linux-musl --release
    - run: mv target/x86_64-unknown-linux-musl/release/kwctl kwctl-linux-x86_64
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: kwctl-linux-x86_64
        path: kwctl-linux-x86_64

  build-linux-aarch64:
    name: Build linux (aarch64) binary
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
    - uses: actions/checkout@v2
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Setup musl for aarch64
      run: |
        curl https://musl.cc/aarch64-linux-musl-cross.tgz | tar -xz
        echo "$PWD/aarch64-linux-musl-cross/bin" >> $GITHUB_PATH
    - run: rustup target add aarch64-unknown-linux-musl
    - name: Build kwctl
      env:
        CC: aarch64-linux-musl-gcc
      run: cargo build --target=aarch64-unknown-linux-musl --release
    - run: mv target/aarch64-unknown-linux-musl/release/kwctl kwctl-linux-aarch64
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: kwctl-linux-aarch64
        path: kwctl-linux-aarch64

  build-darwin-x86_64:
    name: Build darwin (x86_64) binary
    runs-on: macos-latest
    needs:
      - ci
    steps:
    - uses: actions/checkout@v2
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: rustup target add x86_64-apple-darwin
    - name: Build kwctl
      run: cargo build --target=x86_64-apple-darwin --release
    - run: mv target/x86_64-apple-darwin/release/kwctl kwctl-darwin-x86_64
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: kwctl-darwin-x86_64
        path: kwctl-darwin-x86_64

  build-windows-x86_64:
    name: Build windows (x86_64) binary
    runs-on: windows-latest
    needs:
      - ci
    steps:
    - uses: actions/checkout@v2
    - name: Setup rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: rustup target add x86_64-pc-windows-msvc
    - name: Build kwctl
      run: cargo build --target=x86_64-pc-windows-msvc --release
    - run: mv target/x86_64-pc-windows-msvc/release/kwctl.exe kwctl-windows-x86_64.exe
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: kwctl-windows-x86_64
        path: kwctl-windows-x86_64.exe

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - build-linux-x86_64
      - build-linux-aarch64
      - build-darwin-x86_64
      - build-windows-x86_64
    steps:
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release kwctl ${{ github.ref }}
        draft: false
        prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}

    - name: Download linux-x86_64 binary
      uses: actions/download-artifact@v2
      with:
        name: kwctl-linux-x86_64
    - name: Publish linux-x86_64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_name: kwctl-linux-x86_64
        asset_path: kwctl-linux-x86_64
        asset_content_type: application/octet-stream

    - name: Download linux-aarch64 binary
      uses: actions/download-artifact@v2
      with:
        name: kwctl-linux-aarch64
    - name: Publish linux-aarch64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_name: kwctl-linux-aarch64
        asset_path: kwctl-linux-aarch64
        asset_content_type: application/octet-stream

    - name: Download darwin-x86_64 binary
      uses: actions/download-artifact@v2
      with:
        name: kwctl-darwin-x86_64
    - name: Publish darwin-x86_64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_name: kwctl-darwin-x86_64
        asset_path: kwctl-darwin-x86_64
        asset_content_type: application/octet-stream

    - name: Download windows-x86_64 binary
      uses: actions/download-artifact@v2
      with:
        name: kwctl-windows-x86_64
    - name: Publish windows-x86_64 binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_name: kwctl-windows-x86_64.exe
        asset_path: kwctl-windows-x86_64.exe
        asset_content_type: application/octet-stream
