
[toolchain]
channel = "1.92.0"
components = ["clippy", "rust-analyzer", "rustfmt"]
profile = "minimal"
targets = [
  "wasm32-wasip1",
  "aarch64-unknown-linux-musl",
  "x86_64-unknown-linux-musl",
]
