
[toolchain]
channel = "1.92.0"
components = [
  "clippy",
  "llvm-tools-preview", # for cargo-llvm-cov
  "rust-analyzer",
  "rustfmt",
]
profile = "minimal"
targets = [
  "aarch64-unknown-linux-musl",
  "wasm32-wasip1",
  "x86_64-unknown-linux-musl",
]
