[package]
name = "policy-server"
version = "1.1.2"
authors = [
  "Kubewarden Developers <kubewarden@suse.de>",
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.de>",
  "José Guilherme Vanz <jguilhermevanz@suse.com>"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
itertools = "0.10.5"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.4.11" }
lazy_static = "1.4.0"
clap = { version = "4.0", features = [ "cargo", "env" ] }
k8s-openapi = { version = "0.16.0", default-features = false, features = ["v1_25"] }
warp = { version = "0.3.3", default_features = false, features = [ "multipart", "tls"] }
num_cpus = "1.13.1"
opentelemetry = { version = "0.17", default-features = false, features = ["metrics", "trace", "rt-tokio", "serialize"] }
opentelemetry-otlp = { version = "0.10.0", features = ["metrics", "tonic"] }
rayon = "1.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.13"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["ansi", "fmt", "json"] }
tracing-futures = "0.2"
tracing-opentelemetry = "0.17.4"

[dev-dependencies]
tempfile = "3.3.0"
