[package]
name = "policy-server"
version = "1.7.0-rc1"
authors = [
  "Kubewarden Developers <kubewarden@suse.de>",
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.de>",
  "José Guilherme Vanz <jguilhermevanz@suse.com>"
]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.2", features = [ "cargo", "env" ] }
daemonize = "0.5"
humansize = "2.1"
itertools = "0.11.0"
k8s-openapi = { version = "0.18.0", default-features = false, features = ["v1_26"] }
lazy_static = "1.4.0"
num_cpus = "1.16.0"
opentelemetry-otlp = { version = "0.10.0", features = ["metrics", "tonic"] }
opentelemetry = { version = "0.17", default-features = false, features = ["metrics", "trace", "rt-tokio", "serialize"] }
procfs = "0.15"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.11.1" }
rayon = "1.6"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.25"
tokio = { version = "^1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-opentelemetry = "0.17.4"
tracing-subscriber = { version = "0.3", features = ["ansi", "fmt", "json"] }
warp = { version = "0.3.5", default_features = false, features = [ "multipart", "tls"] }
semver = { version = "1.0.18", features = ["serde"] }

[dev-dependencies]
rstest = "0.18"
tempfile = "3.7.0"
