[package]
name = "policy-server"
version = "1.10.0-rc1"
authors = [
  "Kubewarden Developers <kubewarden@suse.de>",
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.de>",
  "José Guilherme Vanz <jguilhermevanz@suse.com>",
]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["cargo", "env"] }
daemonize = "0.5"
humansize = "2.1"
itertools = "0.12.0"
k8s-openapi = { version = "0.20.0", default-features = false, features = [
  "v1_28",
] }
lazy_static = "1.4.0"
num_cpus = "1.16.0"
opentelemetry-otlp = { version = "0.14.0", features = ["metrics", "tonic"] }
opentelemetry = { version = "0.21", default-features = false, features = [
  "metrics",
  "trace",
] }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
procfs = "0.16"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.13.1" }
rayon = "1.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.30"
sha2 = "0.10"
thiserror = "1.0"
tokio = { version = "^1.35.1", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3", features = ["ansi", "fmt", "json"] }
warp = { version = "0.3.6", default_features = false, features = [
  "multipart",
  "tls",
] }
semver = { version = "1.0.21", features = ["serde"] }
mockall_double = "0.3"

[dev-dependencies]
mockall = "0.12"
rstest = "0.18"
tempfile = "3.9.0"
reqwest = { version = "0.11", default_features = false, features = [
  "blocking",
  "json",
  "rustls-tls-native-roots",
] }
