[package]
name = "policy-server"
version = "1.11.0-rc2"
authors = [
  "Kubewarden Developers <kubewarden@suse.de>",
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.de>",
  "José Guilherme Vanz <jguilhermevanz@suse.com>",
]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["cargo", "env"] }
daemonize = "0.5"
futures = "0.3"
humansize = "2.1"
itertools = "0.12.1"
k8s-openapi = { version = "0.21.1", default-features = false, features = [
  "v1_29",
] }
lazy_static = "1.4.0"
mime = "0.3"
num_cpus = "1.16.0"
opentelemetry-otlp = { version = "0.14.0", features = ["metrics", "tonic"] }
opentelemetry = { version = "0.21", default-features = false, features = [
  "metrics",
  "trace",
] }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
procfs = "0.16"
pprof = { version = "0.13", features = ["prost-codec"] }
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.16.2" }
rayon = "1.9"
regex = "1.10"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.32"
sha2 = "0.10"
thiserror = "1.0"
tokio = { version = "^1.36.0", features = ["full"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-opentelemetry = "0.22.0"
tracing-subscriber = { version = "0.3", features = ["ansi", "fmt", "json"] }
semver = { version = "1.0.22", features = ["serde"] }
mockall_double = "0.3"
axum = { version = "0.7.4", features = ["macros", "query"] }
axum-server = { version = "0.6", features = ["tls-rustls"] }
tower-http = { version = "0.5.2", features = ["trace"] }

[dev-dependencies]
mockall = "0.12"
rstest = "0.18"
tempfile = "3.10.1"
tower = { version = "0.4", features = ["util"] }
http-body-util = "0.1.0"
