[package]
name = "policy-server"
version = "0.2.5"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.de>"
]
edition = "2018"

[dependencies]
anyhow = "1.0"
async-stream = "0.3.0"
itertools = "0.10.1"
policy-evaluator = { git = "https://github.com/kubewarden/policy-evaluator", tag = "v0.2.9" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.3.0" }
kubewarden-policy-sdk = "0.3.2"
lazy_static = "1.4.0"
clap = "2.33.3"
futures-util = "0.3.12"
kube = { version = "0.64.0", default-features = false, features = ["client", "rustls-tls"] }
k8s-openapi = { version = "0.13.1", default-features = false, features = ["v1_22"] }
hyper = { version = "0.14", features = ["full"] }
num_cpus = "1.13.0"
opentelemetry = { version = "0.16", default-features = false, features = ["metrics", "trace", "rt-tokio", "serialize"] }
opentelemetry-otlp = { version = "0.9.0", features = ["metrics", "tonic"] }
rustls = "0.20.2"
rustls-pemfile = "0.2.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.23"
tokio = { version = "^1", features = ["full"] }
tokio-rustls = "0.23.1"
tracing = "0.1"
tracing-subscriber = { version= "0.2", features = ["fmt"] }
tracing-futures = "0.2"
tracing-opentelemetry = "0.15.0"

[patch.crates-io]
# Forcing base64ct to version 1.1.1 given that version 1.2.0 has been
# bumped to use Rust 2021 edition. When we see is time, we can bump as
# well, but for now, pin to 1.1.1 that is bound to edition 2018.
base64ct = { git = "https://github.com/RustCrypto/formats.git", tag = "base64ct/v1.1.1" }
