[package]
name = "policy-server"
version = "0.1.0"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-std = "1.9.0"
async-trait = "0.1.42"
async-stream = "0.3.0"
clap = "2.33.3"
futures-util = "0.3.12"
hyper-tls = "0.5.0"
hyper = { version = "0.14", features = ["full"] }
native-tls = "^0.2.1"
num_cpus = "1.13.0"
oci-distribution = "0.4"
openssl = "0.10.32"
serde_yaml = "0.8.15"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio-compat-02 = "0.2.0"
tokio = { version = "^1", features = ["full"] }
tokio-native-tls = "0.3.0"
url = "2.2.0"
wapc = "0.10.1"
wasmtime-provider = "0.0.2"
