[package]
name = "policy-evaluator"
version = "0.5.0"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

[workspace]
members = [
  "crates/burrego"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13.1"
burrego = { path = "crates/burrego" }
cached = "0.40.0"
dns-lookup = "1.0.8"
json-patch = "0.3.0"
kube = { version = "0.76.0", default-features = false, features = ["client", "rustls-tls"] }
k8s-openapi = { version = "0.16.0", default-features = false }
kubewarden-policy-sdk = "0.8.6"
itertools = "0.10"
lazy_static = "1.4.0"
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.7.16" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10"
tokio = { version = "^1", features = ["rt", "rt-multi-thread"] }
tracing = "0.1"
tracing-futures = "0.2"
url = { version = "2.2.2", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }
wasmparser = "0.95.0"
wapc = "1.0.0"
wasmtime-provider = { version = "1.3.2", features = ["cache"] }
picky = { version = "7.0.0-rc.3", default-features = false, features = [ "x509", "ec", "chrono_conversion" ] }
chrono = "0.4.23"


[dev-dependencies]
assert-json-diff = "2.0.2"
k8s-openapi = { version = "0.16.0", default-features = false, features = ["v1_24"] }
