[package]
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.com>",
]
edition = "2021"
name = "policy-evaluator"
version = "0.17.1"

[workspace]
members = ["crates/burrego"]

[dependencies]
anyhow = "1.0"
base64 = "0.22"
burrego = { path = "crates/burrego" }
cached = { version = "0.49", features = ["async_tokio_rt_multi_thread"] }
chrono = { version = "0.4.38", default-features = false }
dns-lookup = "2.0"
futures = "0.3"
email_address = { version = "0.2.4", features = ["serde"] }
itertools = "0.12"
json-patch = "1.0"
k8s-openapi = { version = "0.21.1", default-features = false }
kube = { version = "0.90.0", default-features = false, features = [
  "client",
  "rustls-tls",
  "runtime",
] }
kubewarden-policy-sdk = "0.10.0"
lazy_static = "1.4"
mail-parser = { version = "0.9.3", features = ["serde"] }
picky = { version = "7.0.0-rc.8", default-features = false, features = [
  "chrono_conversion",
  "x509",
] }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.8.5" }
semver = { version = "1.0.22", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
thiserror = "1.0"
time = { version = "0.3.36", features = ["serde-human-readable"] }
tokio = { version = "^1", features = ["rt", "rt-multi-thread"] }
tracing = "0.1"
url = { version = "2.2", features = ["serde"] }
validator = { version = "0.18", features = ["derive"] }
wapc = "1.1"
wasi-common = { workspace = true }
wasmparser = "0.205"
wasmtime = { workspace = true }
wasmtime-provider = { version = "1.16", features = ["cache"] }
wasmtime-wasi = { workspace = true }

[workspace.dependencies]
wasi-common = "19.0"
wasmtime = "19.0"
wasmtime-wasi = "19.0"

[dev-dependencies]
assert-json-diff = "2.0"
test-log = "0.2.15"
k8s-openapi = { version = "0.21.1", default-features = false, features = [
  "v1_28",
] }
rstest = "0.19"
serial_test = "3.0"
test-context = "0.3"
tempfile = "3.8.1"
tower-test = "0.4"
hyper = { version = "1.2.0" }
# This is required to have reqwest built using the `rustls-tls-native-roots`
# feature across all the transitive dependencies of policy-fetcher
# This is required to have the integration tests use the system certificates instead of the
# ones bundled inside of rustls. This allows to pull the test policies also from
# self hosted registries (which is great at development time)
reqwest = { version = "0", default-features = false, features = [
  "rustls-tls-native-roots",
] }
