[package]
name = "policy-evaluator"
version = "0.2.5"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

[workspace]
members = [
  "crates/burrego"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13.0"
burrego = { path = "crates/burrego" }
cached = "0.26.2"
hyper = { version = "0.14" }
json-patch = "0.2.6"
k8s-openapi = { version = "0.13.0", default-features = false, features = ["v1_22"] }
kube = { version = "0.64.0", default-features = false, features = ["client", "rustls-tls"] }
kubewarden-policy-sdk = "0.2.2"
lazy_static = "1.4.0"
oci-distribution = { git = "https://github.com/krustlet/oci-distribution", rev = "96f19570e7f9dd56ed9cce8c9e8095e7c2d7753b" }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.2.2" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "^1", features = ["rt", "rt-multi-thread"] }
tracing = "0.1"
tracing-futures = "0.2"
validator = { version = "0.13", features = ["derive"] }
wapc = "0.10.1"
wasmparser = "0.78.0"
wasmtime-provider = "0.0.5"

[dev-dependencies]
assert-json-diff = "2.0.1"
