[package]
name = "policy-evaluator"
version = "0.4.2"
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>"
]
edition = "2018"

[workspace]
members = [
  "crates/burrego"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
base64 = "0.13.0"
burrego = { path = "crates/burrego" }
cached = "0.35.0"
dns-lookup = "1.0.8"
json-patch = "0.2.6"
kube = { version = "0.73.1", default-features = false, features = ["client", "rustls-tls"] }
k8s-openapi = { version = "0.15.0", default-features = false }
kubewarden-policy-sdk = "0.6.2"
lazy_static = "1.4.0"
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.7.8" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "^1", features = ["rt", "rt-multi-thread"] }
tracing = "0.1"
tracing-futures = "0.2"
url = { version = "2.2.2", features = ["serde"] }
validator = { version = "0.15", features = ["derive"] }
wasmparser = "0.86.0"
wapc = "1.0.0"
wasmtime-provider = "1.0.1"

[dev-dependencies]
assert-json-diff = "2.0.1"
k8s-openapi = { version = "0.15.0", default-features = false, features = ["v1_24"] }
