[package]
authors = [
  "Flavio Castelli <fcastelli@suse.com>",
  "Rafael Fernández López <rfernandezlopez@suse.com>",
  "Víctor Cuadrado Juan <vcuadradojuan@suse.com>",
]
edition = "2021"
name = "policy-evaluator"
version = "0.11.5"

[workspace]
members = ["crates/burrego"]

[dependencies]
anyhow = "1.0"
base64 = "0.21"
burrego = { path = "crates/burrego" }
cached = { version = "0.45", features = ["async_tokio_rt_multi_thread"] }
chrono = { version = "0.4.31", default-features = false }
dns-lookup = "2.0"
email_address = { version = "0.2.4", features = ["serde"] }
itertools = "0.11"
json-patch = "1.0"
k8s-openapi = { version = "0.20.0", default-features = false }
kube = { version = "0.86.0", default-features = false, features = [
  "client",
  "rustls-tls",
] }
kubewarden-policy-sdk = "0.9.8"
lazy_static = "1.4"
mail-parser = { version = "0.9.1", features = ["serde"] }
picky = { version = "7.0.0-rc.8", default-features = false, features = [
  "chrono_conversion",
  "x509",
] }
policy-fetcher = { git = "https://github.com/kubewarden/policy-fetcher", tag = "v0.8.1" }
semver = { version = "1.0.19", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.10"
thiserror = "1.0"
time = { version = "0.3.29", features = ["serde-human-readable"] }
tokio = { version = "^1", features = ["rt", "rt-multi-thread"] }
tracing = "0.1"
tracing-futures = "0.2"
url = { version = "2.2", features = ["serde"] }
validator = { version = "0.16", features = ["derive"] }
wapc = "1.0.0"
wasi-cap-std-sync = { workspace = true }
wasi-common = { workspace = true }
wasmparser = "0.113"
wasmtime = { workspace = true }
wasmtime-provider = { version = "1.10.0", features = ["cache"] }
wasmtime-wasi = { workspace = true }

[workspace.dependencies]
wasi-cap-std-sync = "13.0"
wasi-common = "13.0"
wasmtime = "13.0"
wasmtime-wasi = "13.0"

[dev-dependencies]
assert-json-diff = "2.0"
k8s-openapi = { version = "0.20.0", default-features = false, features = [
  "v1_28",
] }
