[advisories]
ignore = [
  "RUSTSEC-2020-0071", # `time` localtime_r segfault -- https://rustsec.org/advisories/RUSTSEC-2020-0071
  # This vulnerability is currently not affecting chrono 0.4.20+
  # See https://github.com/chronotope/chrono/issues/602
  # Chrono 0.5 will upgrade this depependency, but this will lead
  # to API breakages.
  #
  # This is a transitive depependency
  "RUSTSEC-2021-0147", # This is about "daemonize" being unmaintained.
  # This is a feature that we use only when doing e2e tests
  "RUSTSEC-2020-0168", # This is about "mach" being unmaintained.
  # This is a transitive dependency of wasmtime. This is
  # being tracked upstream via https://github.com/bytecodealliance/wasmtime/issues/6000
  #
  # This is a transitive depependency of sigstore
  "RUSTSEC-2023-0071", # "Classic" RSA timing sidechannel attack from non-constant-time implementation.
  # Okay for local use.
  # https://rustsec.org/advisories/RUSTSEC-2023-0071.html
]
