[advisories]
ignore = [
  "RUSTSEC-2020-0071", # `time` localtime_r segfault -- https://rustsec.org/advisories/RUSTSEC-2020-0071
                       # This vulnerability is currently not affecting chrono 0.4.20+
                       # See https://github.com/chronotope/chrono/issues/602
                       # Chrono 0.5 will upgrade this depependency, but this will lead
                       # to API breakages.
                       #
                       # This is a transitive depependency
  "RUSTSEC-2021-0146", # This is about `twoway` not being maintained anymore
                       # This is a transitive dependency of `multipart`, which is
                       # a dependency of `warp`. This is the GH issue that describes
                       # the problem: # https://github.com/abonander/multipart/issues/143
]
