[advisories]
ignore = [
  "RUSTSEC-2020-0071", # `time` localtime_r segfault -- https://rustsec.org/advisories/RUSTSEC-2020-0071
                       # This vulnerability is currently not affecting chrono 0.4.20+
                       # See https://github.com/chronotope/chrono/issues/602
                       # Chrono 0.5 will upgrade this depependency, but this will lead
                       # to API breakages.
                       #
                       # This is a transitive depependency
]
