pipelineid: release_pr # PR branch will be named: updatecli_main_release_pr

# pr contains the pull request settings that can be overridden
pr:
  labels:
    - "kind/chore"
    - "area/release"
    - "ci-full" # this triggers all CI jobs
  reviewers:
    - "kubewarden/kubewarden-developers"
