github:
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main" # change in pipeline call to `updatecli_main_release_pr`
  author: "kubewarden-controller bot"
  email: "kubewarden-controller-bot@users.noreply.github.com"
  owner: "kubewarden"
  repo: "kubewarden-controller"

pipelineid: release_pr # PR branch will be named: updatecli_main_release_pr

# pr contains the pull request settings that can be overridden
pr:
  labels:
    - "kind/chore"
    - "area/release"
  reviewers:
    - "kubewarden/kubewarden-developers"
