[package]
name = "burrego"
version = "0.1.3"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.60"
base64 = "0.13.0"
chrono = "0.4.20"
chrono-tz = "0.6.3"
gtmpl = "0.7.1"
gtmpl_value = "0.5.1"
itertools = "0.10.3"
json-patch = "0.2.6"
lazy_static = "1.4.0"
regex = "1.5.6"
semver = "1.0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.83"
serde_yaml = "0.9.4"
tracing = "0.1"
tracing-subscriber = { version= "0.3", features = ["fmt", "env-filter"] }
url = "2.2.2"
wasmtime = "0.38.1"

[dev-dependencies]
assert-json-diff = "2.0.2"
clap = { version = "3.1", features = [ "derive" ] }
