[package]
name = "burrego"
version = "0.1.1"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.28.0"
anyhow = "1.0.40"
serde_json = "1.0.64"
clap = "2.33.3"
gtmpl = { git = "https://github.com/flavio/gtmpl-rust.git", branch = "printf-handle-array-and-map" }
gtmpl_value = "0.5.1"
lazy_static = "1.4.0"
tracing = "0.1"
tracing-subscriber = { version= "0.2", features = ["fmt"] }
