apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubewarden-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "kubewarden-controller.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubewarden-controller-manager
subjects:
- kind: ServiceAccount
  name: {{ include "kubewarden-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubewarden-controller-manager-cluster-role
  labels:
    {{- include "kubewarden-controller.labels" . | nindent 4 }}
  annotations:
    {{- include "kubewarden-controller.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubewarden-controller-manager
subjects:
- kind: ServiceAccount
  name: {{ include "kubewarden-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
